# Generated by Django 4.2.21 on 2025-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'product1',
            },
        ),
    ]
