# Generated by Django 4.2.21 on 2025-07-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'phone',
            },
        ),
    ]
