# Generated by Django 4.2.21 on 2025-08-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('modeltype', models.CharField(choices=[('suv', 'SUV'), ('hatchback', 'hatchback'), ('sedan', 'SEDAN')])),
            ],
            options={
                'db_table': 'models',
            },
        ),
    ]
