# Generated by Django 4.2.21 on 2025-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
