# Generated by Django 4.2.21 on 2025-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
    ]
