# Generated by Django 4.2.21 on 2025-05-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_product_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
